version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
profile = "ccj-webproduct-develop"
stack_name = "ccv-traning-aws"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-142a9mlrpeapx"
s3_prefix = "ccv-traning-aws"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Product=\"ccv-traning-aws\" Env=\"dev\""
image_repositories = []
tags = "Product=\"ccv-traning-aws\" Environment=\"develop\" Owner=\"ccv\""